swagger: '2.0'
info:
  version: v1
  title: Provider server
  termsOfService: None
basePath: /
paths:
  /Controller/Validate:
    post:
      tags:
        - Controller
      summary: Validate information
      description: Validate the users information
      operationId: validate
      consumes:
        - application/json
        - text/json
        - application/json-patch+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: username
          in: query
          description: Username to login
          required: true
          type: string
        - name: password
          in: query
          description: Password to login
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'

  /Controller/GetSuppliers:
    post:
      tags: 
        - Controller
      summary: Henter suppliers
      operationId: getSupplier
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Page'
              
  /Controller/AddNoteToSupplier:
    post:
      tags:
        - Controller
      summary: Tilføjer en note til en supplier
      operationId: addNoteToSupplier
      consumes:
        - application/json
        - text/json
        - application/json-patch+json
      parameters:
        - name: supplierName
          in: query
          required: true
          type: string
        - name: editor
          in: query
          required: true
          type: string
        - name: text
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ok
          
definitions:
  User:
    description: Information about the user
    type: object
    properties:
      username: 
        description: The username of the user
        type: string
      rights:
        description: The rights of the user
        type: string
        enum: [Admin, Provia, Supplier]
  Product:
    description: Informations about a product
    type: object
    properties:
      productName: 
        description: The name of the product
        type: string
      description:
        description: The description about the product
        type: string
      price:
        description: The price of the product
        type: string
      packaging:
        description: The packaging of the product
        type: string
  Page:
    description: Page containing information about a supplier
    type: object
    properties:
      owner:
        description: The owner of the page => The supplier
        type: string
      products:
        description: The suppliers products
        type: array
        items: 
            $ref: '#/definitions/Product'
      note:
        $ref: '#/definitions/Note'
  Note: 
    description: A note on the supplier page
    type: object
    properties:
      text:
        type: string
      editor:
        type: string
      creationDate:
        type: string
        format: date
                
        
securityDefinitions: {}